title: About Tobias Gunkel
remote_theme: "brianmaierjr/uni"
#remote_theme: "sharu725/online-cv"
#remote_theme: "sabhn/portfolio"
content: Coming Soon
#sharing_image:
social:
  - platform: GitHub
    url: https://github.com/tobigun
  - platform: Xing
    url: https://www.xing.com/profile/Tobias_Gunkel4
plugins:
  - jekyll-remote-theme
