title: About Tobias Gunkel
remote_theme: "brianmaierjr/uni"
#theme: minima
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-gfm-admonitions  
#  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: true
